{% set name = "loky" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0002550260606faae99e3df75c36c3f242f94b3c4788741d8c3dbad1e6eb7f1

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - cloudpickle
    - psutil

test:
  imports:
    - loky

about:
  home: https://github.com/tomMoral/loky
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/tomMoral/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
