{% set name = "loky" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87f7d4089a0c2be65f961eb46c1c26749afe58a299cc0d14ddec436e897b7af6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - cloudpickle
    - psutil

test:
  imports:
    - loky

about:
  home: https://github.com/tomMoral/loky
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/tomMoral/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
