{% set name = "loky" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f7804a80011c8c32d2dc896f52a34688be88bac0c7e1e767fc89f8ba402bd29

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - cloudpickle
    - psutil

test:
  imports:
    - loky

about:
  home: https://github.com/tomMoral/loky
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/tomMoral/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
