{% set name = "loky" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd8750b24b283a579bafaf0631d114aa4487c682aef6fce01fa3635336297fdf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >= 3.6
    - pip
  run:
    - python >= 3.6
    - cloudpickle
    - psutil

test:
  imports:
    - loky

about:
  home: https://github.com/joblib/loky
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/joblib/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
    - ogrisel
    - pierreglaser
