{% set name = "loky" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2190f938bd07ad809a88ee0fe652e44c816f612d672889b5e76dbb9b089adfcd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cloudpickle

test:
  imports:
    - loky
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joblib/loky
  dev_url: https://github.com/joblib/loky
  doc_url: https://loky.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Robust and reusable Executor for joblib
  description: |
    A robust, cross-platform and cross-version implementation of 
    concurrent.futures.ProcessPoolExecutor with many features.

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
    - ogrisel
    - pierreglaser
