{% set name = "loky" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbe10cd89603193da80529c6cdab901dd6a4176f0e749ba6f5eb775e352b1e73

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cloudpickle
    - psutil

test:
  imports:
    - loky

about:
  home: https://github.com/joblib/loky
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/joblib/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
    - ogrisel
    - pierreglaser
