travis:
  secure:
    BINSTAR_TOKEN: W3MZXeopdTk9PT5EwubXw4Rqe2UOMcwEl0r4iKh7mjEJtNeLfzIwKAw/swKsT6iyDoBDlOF5tYdbvDxA7+YFgtGb5vinleGwtSh7Ietmzr8zzBt4cbZl89DpuaHIMO8ByTDxoUPd+REAT/eiPPdI3NpLExKJn/qjqM2CyUc15Pv2JSpYvgThn/tkdsknGZEAmmlIaUeoQ154jLps3xhAe4b++SlSiQvozU2HWKZWF/bwRzv2/aSJeEmJ+YMUkIQibSKdGJ2jCq8C4+q4inVhxpqgYpXUXJ4xuGNAcZu2RdLlF8qroPOpJoicyBTmywUFXPRqi3Uq8zDBfkCk1vwoa1t91XAEk0Qt05S89Ro/b4OvzMkB4znwiEbwr6Ql8JCLDOCfGfwG2vnQ2QnxdyGiqRts7IEJ1wFcy8t8dQn6xLfVNCv1PxF39k5ZUhn+l0NdjY62bQ9Se7qM5mqmuOJSXVt640eclQlIFxj+rXlddIfU2qix/Auj/QQAkFqCYAZ2ThIlR0KljM5pMoD+CGzcGaksC/NWWccGgwrpKm8Ixv8HqJf9mW6sF+2uKYfbS+1VQy8lVo0/B6ggnUCdJ2xBgXnn9FxhXT4/4zf4KM8a44B7JwiAj5uq2DF69f/Xbtin30IbL19MTfNxY9CJrfkbmuQpsZKikEplqhbDEZ4URLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
