travis:
  secure:
    BINSTAR_TOKEN: gyGUfavMb3/QoJDfnUpH+tR+P/9WPVHMWFQQMxDEuMYXvWMF+ULWVnWeIGKZ4TN84r5iMvubx6XGbDxI2jvBKj+RNFh81M217Ypy8ktJh5LBOYgKABH8Llk9C7wuhzk+T0CTdj169yUsbNgWbLZ6R+PXXxmLNsooCY3ukpeKB9MU0NpYzAHAIgkxbiDlJ/1S2YZ4OlIQJ2vxas1K14VcXts5vzb5znjUfuGxTmoka1byAUAdhpouf2+gNopYwNYfMvjEXN/h4yz1tiKegXZV9boTOqsJWsnxFUj4AHIpquo9KIOLh6ZUjD+2dyXGOEkoqs6IBB9casv+sB/2YAdJarbwz2PLOHmURQ/S8wVyNsEZLX4FfuY/FOyVIjeuY4gn0oxQJ+tFCSCw/Sd+RZ+PEsh40JHrtXi5Jwl3SjfnEOp+SVteupppqL3XMT0T6SaXvDdthpZ5pw1OWK9dHHDCHC2afqIcMmVReiHmXRkjI0//3cQFy3Jv39obuHFufuCa0Zb74kqbQjO23dIPevDHiOKgIfLjMd5AnDp4D81besgxpbSw75eJnwzlsd7zKAvJsimUW06sA3ULmBzkatU6AZS/XB8pJKN5iDEXWLsFAjmxucOBqd2T8GoCRbQxP+zd7YkCh7Gc/rTvhEajayMuqa5Mn76rTGiC20zdhHvIRzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
